stages:
  - test
  - release
  - publish

variables:
  GIT_STRATEGY: fetch

cache:
  key: "$CI_PROJECT_NAME-$CI_BUILD_REF_NAME"
  paths:
    - frontend/node_modules


backend-test:
  stage: test
  retry: 2 # many retries, but until can be fixed too many eisenbugs
  script:
    - cd $CI_PROJECT_DIR
    - scripts/backend-test.py
  artifacts:
    paths:
      - log
    expire_in: 1 week
    when: always
  cache:
    paths:
      - backend/_build
      - backend/deps

frontend-test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - scripts/frontend-test.py
  cache:
    paths:
      - backend/_build
      - backend/deps
      - frontend/node_modules
      - frontend/dist
  artifacts:
    paths:
      - log
    expire_in: 1 week
    when: always

integration-test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - scripts/integration-test.py
  cache:
    paths:
      - backend/_build
      - backend/deps
      - frontend/node_modules
      - frontend/dist
  artifacts:
    paths:
      - frontend/shots
      - log
    expire_in: 1 week
    when: always
  allow_failure: true
  only:
    - skip

plugins-test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - scripts/plugin-test.py
  artifacts:
    paths:
      - log
    expire_in: 1 week
    when: always
  cache:
    paths:
      - backend/_build
      - backend/deps

release:
  stage: release
  script:
    - scripts/version-update.sh
    - make deb
  tags:
    - ubuntu1604
    - gpg
  artifacts:
    paths:
      - serverboards.deb
    expire_in: 1 week
  only:
    - master
    - disitillery

publish-unstable:
  stage: publish
  script:
    - sudo -H /usr/local/bin/publish-unstable
  dependencies:
    - release
  variables:
    DEBSIGN_KEYID: C1FCABC2
  tags:
    - ubuntu1604
    - rsync-www
  only:
    - master
  when: manual
